language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
script:
- mkdir upload
- "./updateBuildVersion.sh"
- sed -i "s/MYWLANSSID/$WLANSSID/g"     src/network.h
- sed -i "s/MYWLANPASSWD/$WLANPASSWD/g" src/network.h
- sed -i "s/MYMQTTSERVER/$MQTTSERVER/g" src/mqtthandle.h
- platformio run
- cp .pioenvs/huzzah/firmware.bin upload/blouse.bin
deploy:
  provider: s3
  bucket: feelflight
  skip_cleanup: true
  acl: public_read
  local_dir: upload/
  upload-dir: firmware
  secret_access_key:
    secure: Qu/SGjbUzV9VaG7c1siCeP6W4YrUBPxrPHY7tb8l8QaEQvCN9mr0SW3U5MMH58z9STcNKfpiEI7+1kdgXR23JdC7nvqQTdBof1Lwl2dvNMtwEYazHBikf1ES5CRivY2l4ZAGmf5ehLilVed9Gtd79t2luF10wsB4iHiNwItQzfRXnzSDMNGGzIQpqQ6ucybX8/S1URDFgl4tAVFyFMhe09OyAS+VtiN6gnDms+5daHGTudQEpDkaA4fBFMN++Z6BVjTVsitsyrLxJe1gPyBD9AzOS/xU78X0MtDniOIQcrbbhUGvg88KAFVkn8Giq86c60t8IsneQqS0I6tqwOW8aW8yCwOjJqzF8/U86PmAVMalhNW66FUIBTBrjtu4OO/GhMpmi/3ILCm2Um4IEuHRdXihf5S9uUSM+7mtc2Dn0Bd4fiL4wu4kTXhU+Q07ebGxeux4UypP/g65IudqPfRuqiMzBYWtr8huPEm/3+pEo8CTnELnzPiSW+Uh++vt6MESuf6MhpLBsQNEg5mmBItO3IsL5v63i4TTv4FReO2DPT7Bz3GfhmjxLKjJK05kQi98ajyYbOVv0f5rtkgzPc63z2vjX4I0c2cQqGo+i/saFnThh5p/KH+n81bxGpmrsQ3YdNsOpXEla1Zb2iUNG04oVAXUXtYblazAWfR73LLrYQw=
  access_key_id:
    secure: z43RpmCafH4vDG6okzU9YFGcfjk9IT5yLvrCG6AEYJ+TRs9IYK8Mw7AWWplixcTGYr8AQbuvAHM8VoDaZ3DjrSn9qgACwiozoGZ7dzocMcn0BZrt5V2QtYbqlc8ZpiQ2AicA3lGdjUpM6xNfKnupRnS9hdMZKQu3OWmS/cZJJov5WlQLi4lStyyCRAgcrt1LxL1pjyjqrYcqcIdDhyB3D+FsFztt5kYYV/ntfxx+pA9d+k7q7sjhBqYg+GibhS6sX90Kz2UaEZzlWCv31LLB7jbg9IyqET6+wWVD1RvHro0z32FfabSMggWPs5N7YmEQ84YXwV08NFGVzYExTrLOfoyfV8Bppi/Bt+EKOdl75MNZSGELuL13NdqvNE2e47YoEltuo0wrGYU90yX0O9Y+Wm3zAqK1uXDHRly78Rx14pktAFBGdHI/n+8hQYyzIU0SGXkMdhG3HHQcNyX7zFKQSHJc97CWCziASdj2whQajDV2HU2SDszw8Em+VSF2jorvFVcPISgWiFoYpaqomIeLUWvbqs8tFAiMovRAO8vpTsVClAkL0mzU8q9foj+r9+0CqoUJmdsb39FE0NfJQMWS+Kg4C/V/yaOyG0YnmlKgflEHm0pCZwj4dBza2YPBeXcKYwushsECvnfhd38tHrRyvWnb6IOfJjZcfE1fcv8LfNU=
